import { Plant } from './types'

// Optimalwerte & Blühzeiten orientiert am deutschen Trachtkalender (Schwerpunkt
// Hessen / Mitteldeutschland). Blühzeiten sind Richtwerte und werden durch
// Imkermeldungen + Wetter dynamisch verfeinert.
export const PLANTS: Plant[] = [
  {
    id: 'salweide',
    name: 'Salweide',
    temp: { min: 8, opt: 15, max: 22 },
    humidity: { min: 45, opt: 65, max: 85 },
    rainBeneficial: false,
    maxWind: 18,
    nectar: 'mittel',
    pollen: 'sehr hoch',
    bloomStart: [3, 10],
    bloomEnd: [4, 15],
    taxon: 'Salix caprea',
    description: 'Erste wichtige Pollenquelle im Frühjahr – entscheidend für die Brutentwicklung.',
  },
  {
    id: 'obstbluete',
    name: 'Obstblüte',
    temp: { min: 12, opt: 18, max: 25 },
    humidity: { min: 45, opt: 60, max: 80 },
    rainBeneficial: false,
    maxWind: 14,
    nectar: 'hoch',
    pollen: 'hoch',
    bloomStart: [4, 10],
    bloomEnd: [5, 10],
    taxon: 'Malus domestica',
    description: 'Apfel, Kirsche, Birne & Co. – ergiebige Frühtracht und wichtig für die Bestäubung.',
  },
  {
    id: 'loewenzahn',
    name: 'Löwenzahn',
    temp: { min: 12, opt: 18, max: 26 },
    humidity: { min: 45, opt: 60, max: 80 },
    rainBeneficial: false,
    maxWind: 16,
    nectar: 'hoch',
    pollen: 'sehr hoch',
    bloomStart: [4, 15],
    bloomEnd: [5, 25],
    taxon: 'Taraxacum officinale',
    description: 'Massentracht auf Wiesen – kann zu schnellem Nektareintrag und Schwarmstimmung führen.',
  },
  {
    id: 'raps',
    name: 'Raps',
    temp: { min: 12, opt: 17, max: 25 },
    humidity: { min: 35, opt: 57, max: 80 },
    rainBeneficial: false,
    maxWind: 10,
    nectar: 'sehr hoch',
    pollen: 'hoch',
    bloomStart: [4, 20],
    bloomEnd: [5, 31],
    taxon: 'Brassica napus',
    description: 'Wichtigste Frühjahrsmassentracht. Nässe reduziert den Nektar; Honig kristallisiert schnell.',
  },
  {
    id: 'robinie',
    name: 'Robinie (Scheinakazie)',
    temp: { min: 15, opt: 20, max: 27 },
    humidity: { min: 45, opt: 67, max: 85 },
    rainBeneficial: true,
    maxWind: 12,
    nectar: 'sehr hoch',
    pollen: 'gering',
    bloomStart: [5, 20],
    bloomEnd: [6, 15],
    taxon: 'Robinia pseudoacacia',
    description: 'Liefert den begehrten „Akazienhonig“. Kurze, wetterabhängige Blüte – Timing ist alles.',
  },
  {
    id: 'winterlinde',
    name: 'Linde (Winterlinde)',
    temp: { min: 18, opt: 23, max: 28 },
    humidity: { min: 40, opt: 70, max: 85 },
    rainBeneficial: true,
    maxWind: 15,
    nectar: 'sehr hoch',
    pollen: 'hoch',
    bloomStart: [6, 10],
    bloomEnd: [7, 5],
    taxon: 'Tilia cordata',
    description: 'Hochsommer-Spitzentracht. Warme, schwüle Tage mit etwas Feuchte ergeben höchste Erträge.',
  },
  {
    id: 'sommerlinde',
    name: 'Linde (Sommerlinde)',
    temp: { min: 18, opt: 23, max: 28 },
    humidity: { min: 40, opt: 70, max: 85 },
    rainBeneficial: true,
    maxWind: 15,
    nectar: 'sehr hoch',
    pollen: 'hoch',
    bloomStart: [6, 25],
    bloomEnd: [7, 20],
    taxon: 'Tilia platyphyllos',
    description: 'Verlängert die Lindentracht in den Juli hinein.',
  },
  {
    id: 'phacelia',
    name: 'Phacelia (Bienenfreund)',
    temp: { min: 14, opt: 20, max: 28 },
    humidity: { min: 40, opt: 60, max: 80 },
    rainBeneficial: false,
    maxWind: 14,
    nectar: 'hoch',
    pollen: 'hoch',
    bloomStart: [6, 15],
    bloomEnd: [9, 15],
    taxon: 'Phacelia tanacetifolia',
    description: 'Beliebte Zwischenfrucht/Blühstreifen – verlässliche Sommer- und Spättracht.',
  },
  {
    id: 'honigtau',
    name: 'Honigtau (Wald)',
    temp: { min: 18, opt: 24, max: 32 },
    humidity: { min: 40, opt: 60, max: 80 },
    rainBeneficial: false,
    maxWind: 15,
    nectar: 'sehr hoch',
    pollen: 'gering',
    bloomStart: [6, 25],
    bloomEnd: [8, 31],
    description: 'Ausscheidungen von Blatt-/Schildläusen auf Fichte, Tanne, Eiche. Warm & trocken begünstigt – Regen unterbricht.',
  },
  {
    id: 'heide',
    name: 'Heide (Besenheide)',
    temp: { min: 14, opt: 20, max: 27 },
    humidity: { min: 45, opt: 65, max: 85 },
    rainBeneficial: false,
    maxWind: 16,
    nectar: 'hoch',
    pollen: 'hoch',
    bloomStart: [8, 1],
    bloomEnd: [9, 20],
    taxon: 'Calluna vulgaris',
    description: 'Spättracht auf Heideflächen. Gelartiger Honig, der zur Winterfütterung ungeeignet ist.',
  },
  {
    id: 'efeu',
    name: 'Efeu',
    temp: { min: 12, opt: 18, max: 24 },
    humidity: { min: 50, opt: 67, max: 85 },
    rainBeneficial: true,
    maxWind: 12,
    nectar: 'hoch',
    pollen: 'hoch',
    bloomStart: [9, 1],
    bloomEnd: [10, 20],
    taxon: 'Hedera helix',
    description: 'Wichtigste Herbsttracht für den Wintervorrat – oft die letzte Nektarquelle des Jahres.',
  },
]

export const PLANTS_BY_ID: Record<string, Plant> = Object.fromEntries(
  PLANTS.map(p => [p.id, p])
)
