import { Plant } from './types'

// Optimalwerte & Blühzeiten orientiert am deutschen Trachtkalender (Schwerpunkt
// Hessen / Mitteldeutschland). Blühzeiten sind Richtwerte und werden durch
// Imkermeldungen + Wetter dynamisch verfeinert.
export const PLANTS: Plant[] = [
  {
    id: 'salweide',
    name: 'Salweide',
    temp: { min: 8, opt: 15, max: 22 },
    humidity: { min: 45, opt: 65, max: 85 },
    rainBeneficial: false,
    maxWind: 18,
    nectar: 'mittel',
    pollen: 'sehr hoch',
    bloomStart: [3, 10],
    bloomEnd: [4, 15],
    taxon: 'Salix caprea',
    description: 'Erste wichtige Pollenquelle im Frühjahr – entscheidend für die Brutentwicklung.',
  },
  {
    id: 'obstbluete',
    name: 'Obstblüte',
    temp: { min: 12, opt: 18, max: 25 },
    humidity: { min: 45, opt: 60, max: 80 },
    rainBeneficial: false,
    maxWind: 14,
    nectar: 'hoch',
    pollen: 'hoch',
    bloomStart: [4, 10],
    bloomEnd: [5, 10],
    taxon: 'Malus domestica',
    description: 'Apfel, Kirsche, Birne & Co. – ergiebige Frühtracht und wichtig für die Bestäubung.',
  },
  {
    id: 'loewenzahn',
    name: 'Löwenzahn',
    temp: { min: 12, opt: 18, max: 26 },
    humidity: { min: 45, opt: 60, max: 80 },
    rainBeneficial: false,
    maxWind: 16,
    nectar: 'hoch',
    pollen: 'sehr hoch',
    bloomStart: [4, 15],
    bloomEnd: [5, 25],
    taxon: 'Taraxacum officinale',
    description: 'Massentracht auf Wiesen – kann zu schnellem Nektareintrag und Schwarmstimmung führen.',
  },
  {
    id: 'raps',
    name: 'Raps',
    temp: { min: 12, opt: 17, max: 25 },
    humidity: { min: 35, opt: 57, max: 80 },
    rainBeneficial: false,
    maxWind: 10,
    nectar: 'sehr hoch',
    pollen: 'hoch',
    bloomStart: [4, 20],
    bloomEnd: [5, 31],
    taxon: 'Brassica napus',
    description: 'Wichtigste Frühjahrsmassentracht. Nässe reduziert den Nektar; Honig kristallisiert schnell.',
  },
  {
    id: 'robinie',
    name: 'Robinie (Scheinakazie)',
    temp: { min: 15, opt: 20, max: 27 },
    humidity: { min: 45, opt: 67, max: 85 },
    rainBeneficial: true,
    maxWind: 12,
    nectar: 'sehr hoch',
    pollen: 'gering',
    bloomStart: [5, 20],
    bloomEnd: [6, 15],
    taxon: 'Robinia pseudoacacia',
    description: 'Liefert den begehrten „Akazienhonig“. Kurze, wetterabhängige Blüte – Timing ist alles.',
  },
  {
    id: 'sommerlinde',
    name: 'Linde (Sommerlinde)',
    temp: { min: 18, opt: 23, max: 28 },
    humidity: { min: 40, opt: 70, max: 85 },
    rainBeneficial: true,
    maxWind: 15,
    nectar: 'sehr hoch',
    pollen: 'hoch',
    bloomStart: [6, 10],
    bloomEnd: [6, 30],
    taxon: 'Tilia platyphyllos',
    description: 'Blüht rund zwei Wochen vor der Winterlinde und eröffnet die Lindentracht.',
  },
  {
    id: 'winterlinde',
    name: 'Linde (Winterlinde)',
    temp: { min: 18, opt: 23, max: 28 },
    humidity: { min: 40, opt: 70, max: 85 },
    rainBeneficial: true,
    maxWind: 15,
    nectar: 'sehr hoch',
    pollen: 'hoch',
    bloomStart: [6, 25],
    bloomEnd: [7, 20],
    taxon: 'Tilia cordata',
    description: 'Die wichtigste Lindenart für Lindenhonig – blüht später als die Sommerlinde, oft bis in den Juli.',
  },
  {
    id: 'phacelia',
    name: 'Phacelia (Bienenfreund)',
    temp: { min: 14, opt: 20, max: 28 },
    humidity: { min: 40, opt: 60, max: 80 },
    rainBeneficial: false,
    maxWind: 14,
    nectar: 'hoch',
    pollen: 'hoch',
    bloomStart: [6, 15],
    bloomEnd: [9, 15],
    taxon: 'Phacelia tanacetifolia',
    description: 'Beliebte Zwischenfrucht/Blühstreifen – verlässliche Sommer- und Spättracht.',
  },
  {
    id: 'honigtau',
    name: 'Honigtau (Wald)',
    temp: { min: 18, opt: 24, max: 32 },
    humidity: { min: 40, opt: 60, max: 80 },
    rainBeneficial: false,
    maxWind: 15,
    nectar: 'sehr hoch',
    pollen: 'gering',
    bloomStart: [6, 25],
    bloomEnd: [8, 31],
    description: 'Ausscheidungen von Blatt-/Schildläusen auf Fichte, Tanne, Eiche. Warm & trocken begünstigt – Regen unterbricht.',
  },
  {
    id: 'heide',
    name: 'Heide (Besenheide)',
    temp: { min: 14, opt: 20, max: 27 },
    humidity: { min: 45, opt: 65, max: 85 },
    rainBeneficial: false,
    maxWind: 16,
    nectar: 'hoch',
    pollen: 'hoch',
    bloomStart: [8, 1],
    bloomEnd: [9, 20],
    taxon: 'Calluna vulgaris',
    description: 'Spättracht auf Heideflächen. Gelartiger Honig, der zur Winterfütterung ungeeignet ist.',
  },
  {
    id: 'efeu',
    name: 'Efeu',
    temp: { min: 12, opt: 18, max: 24 },
    humidity: { min: 50, opt: 67, max: 85 },
    rainBeneficial: true,
    maxWind: 12,
    nectar: 'hoch',
    pollen: 'hoch',
    bloomStart: [9, 1],
    bloomEnd: [10, 20],
    taxon: 'Hedera helix',
    description: 'Wichtigste Herbsttracht für den Wintervorrat – oft die letzte Nektarquelle des Jahres.',
  },
  {
    id: 'hasel',
    name: 'Hasel',
    temp: { min: 5, opt: 11, max: 18 },
    humidity: { min: 50, opt: 70, max: 90 },
    rainBeneficial: false,
    maxWind: 20,
    nectar: 'gering',
    pollen: 'sehr hoch',
    bloomStart: [2, 1],
    bloomEnd: [3, 20],
    taxon: 'Corylus avellana',
    description: 'Sehr frühe Pollenquelle – erster Reiz für die Brutentwicklung im Spätwinter.',
  },
  {
    id: 'brombeere',
    name: 'Brombeere',
    temp: { min: 15, opt: 22, max: 30 },
    humidity: { min: 45, opt: 65, max: 85 },
    rainBeneficial: false,
    maxWind: 14,
    nectar: 'hoch',
    pollen: 'hoch',
    bloomStart: [6, 1],
    bloomEnd: [8, 15],
    taxon: 'Rubus fruticosus',
    description: 'Langanhaltende Dauertracht an Waldrändern und Hecken – verlässlich von Juni bis August.',
  },
  {
    id: 'weissklee',
    name: 'Weißklee',
    temp: { min: 16, opt: 22, max: 28 },
    humidity: { min: 45, opt: 60, max: 80 },
    rainBeneficial: false,
    maxWind: 14,
    nectar: 'hoch',
    pollen: 'mittel',
    bloomStart: [6, 1],
    bloomEnd: [9, 15],
    taxon: 'Trifolium repens',
    description: 'Wiesen- und Rasentracht über den ganzen Sommer – ergiebig bei warmem, sonnigem Wetter.',
  },
  {
    id: 'natternkopf',
    name: 'Natternkopf (Blauer Lattich)',
    temp: { min: 16, opt: 24, max: 32 },
    humidity: { min: 35, opt: 55, max: 80 },
    rainBeneficial: false,
    maxWind: 18,
    nectar: 'sehr hoch',
    pollen: 'hoch',
    bloomStart: [6, 1],
    bloomEnd: [9, 10],
    taxon: 'Echium vulgare',
    description: 'Hervorragende Nektarpflanze auf Trocken-/Ruderalflächen – schüttet auch bei Hitze stark.',
  },
  {
    id: 'edelkastanie',
    name: 'Edelkastanie',
    temp: { min: 18, opt: 24, max: 30 },
    humidity: { min: 45, opt: 65, max: 85 },
    rainBeneficial: false,
    maxWind: 15,
    nectar: 'hoch',
    pollen: 'sehr hoch',
    bloomStart: [6, 15],
    bloomEnd: [7, 15],
    taxon: 'Castanea sativa',
    description: 'Regionale Sommertracht (v.a. warme Lagen) – kräftiger, würziger Honig.',
  },
  {
    id: 'sonnenblume',
    name: 'Sonnenblume',
    temp: { min: 16, opt: 24, max: 32 },
    humidity: { min: 35, opt: 55, max: 80 },
    rainBeneficial: false,
    maxWind: 16,
    nectar: 'mittel',
    pollen: 'sehr hoch',
    bloomStart: [7, 1],
    bloomEnd: [9, 10],
    taxon: 'Helianthus annuus',
    description: 'Felder & Blühstreifen – wichtige Pollen- und Nektarquelle im Hochsommer.',
  },
  {
    id: 'springkraut',
    name: 'Drüsiges Springkraut',
    temp: { min: 14, opt: 20, max: 27 },
    humidity: { min: 50, opt: 70, max: 90 },
    rainBeneficial: true,
    maxWind: 12,
    nectar: 'sehr hoch',
    pollen: 'hoch',
    bloomStart: [7, 20],
    bloomEnd: [10, 5],
    taxon: 'Impatiens glandulifera',
    description: 'Ergiebige Spättracht an Gewässern – kann den Spätsommer entscheidend auffüllen.',
  },
  {
    id: 'goldrute',
    name: 'Goldrute',
    temp: { min: 15, opt: 22, max: 28 },
    humidity: { min: 45, opt: 60, max: 82 },
    rainBeneficial: false,
    maxWind: 16,
    nectar: 'hoch',
    pollen: 'hoch',
    bloomStart: [8, 1],
    bloomEnd: [10, 10],
    taxon: 'Solidago canadensis',
    description: 'Späte Massentracht auf Brachen – wichtig zum Auffüllen der Winterreserven.',
  },
]

export const PLANTS_BY_ID: Record<string, Plant> = Object.fromEntries(
  PLANTS.map(p => [p.id, p])
)
